#!/bin/bash

model=${1-}       #name of the directory
fname=${2-ehat}  
odir=${3-aniso}

dfile=d65.dat  #check your depth file name



  cd $model/calcpidata
  mkdir aniso
  cd ../..
  i=1
  while [ $i -le 65 ]
  do 
    d=`oneline $i $dfile`
    echo working on $d depth
    paste $model/calcpidata/in.0.2900 $model/calcpidata/ehat.2900 | gawk \
    '{print $2*f, 90-$1*f, $3, $6, $7, $8}' f=57.295779513082320 > $model/calcpidata/$odir/tmp.a
    
    paste $model/calcpidata/in.0.2900 $model/calcpidata/pi.2900 | gawk \
    '{print $2*f, 90-$1*f, $3, $6}' f=57.295779513082320 > $model/calcpidata/$odir/tmp.pi
    
    gawk '{if($3==d) print $1, $2, $3, $4, $5, $6}' \
    d=$d $model/calcpidata/$odir/tmp.a > $model/calcpidata/$odir/anisotropy.$d.v
    
    gawk '{if($3==d && $4!="Infinity") print $1, $2, log($4)/log(10)}' \
    d=$d $model/calcpidata/$odir/tmp.pi > $model/calcpidata/$odir/pi.$d.xyz

    gawk '{print $1,$2,atan2(-$5,$4)*(180/3.14159), 0.3}' \
    $model/calcpidata/$odir/anisotropy.$d.v > $model/calcpidata/ehat.$i.gbl
    
    surface $model/calcpidata/$odir/pi.$d.xyz -G$model/calcpidata/pi.$i.grd -Rd -I0.2 -T0.25 -Lud -Lld

  ((i=i+1))
  done


